### ISSUE TITLE
为什么打开会是乱码这个

### ISSUE THREAD

**Issue by ileadall42** [gary-Shen/hexo-theme-curry#1]
![image](https://user-images.githubusercontent.com/27263086/37820007-484e817e-2eba-11e8-92df-e0246fd8813b.png)
> mac os 详情如下：
![image](https://user-images.githubusercontent.com/27263086/37820018-57237420-2eba-11e8-8646-316b1e569b96.png)
> node -v v8.7.0

**Comment by ileadall42** [comment]
可以了，原来是没有安装依赖。
npm install --save hexo-renderer-jade hexo-generator-feed hexo-generator-sitemap hexo-browsersync hexo-generator-archive 
但是这个要怎么安装依赖呢。

**Comment by gary-Shen** [comment]
@ileadall42 依赖在[package.json](https://github.com/gary-Shen/hexo-theme-curry/blob/master/package.json)里，模板引擎使用的是pug，不是默认的ejs。
