### ISSUE TITLE
请问可以移植这个主题到Hugo嘛？

### ISSUE THREAD

**Issue by sevi418** [gary-Shen/hexo-theme-curry#14]
很喜欢这个主题，很精美！
但是自己很少用Hexo，所以想移植到Hugo，不知道可不可以？

**Comment by gary-Shen** [comment]
谢谢~抱歉现在才看到。
我自己没有过Hugo，所以大可能不会移植。
不过你希望自己可以移植的话，随时都可以。

**Comment by sevi418** [comment]
谢谢回复！
我后来想了一下，不知道自己能不能做到，所以就closed了。
等我有能力了再来移植吧 😥
