### ISSUE TITLE
aboutme页面判断链接的代码似乎失效

### ISSUE THREAD

**Issue by ileadall42** [gary-Shen/hexo-theme-curry#2]
![image](https://user-images.githubusercontent.com/27263086/37826429-6253c962-2ece-11e8-9c8f-7ae8ca115001.png)
![image](https://user-images.githubusercontent.com/27263086/37826444-6d16a6e4-2ece-11e8-9c15-74ba286f8e54.png)
尝试放出链接，但没有执行if的语句。

**Comment by gary-Shen** [comment]
@ileadall42 收到，如果可以的话提PR感激不尽~

**Comment by gary-Shen** [comment]
@ileadall42 已修复~

**Comment by ileadall42** [comment]
@gary-Shen 谢谢你呀，我觉得你这个很好看，这是nodejs那一系列的东西吗？看来要找个机会好好学习下nodejs

**Comment by gary-Shen** [comment]
@ileadall42 🙈
Pug是Nodejs的模板引擎，比ejs更简洁不会看得眼花。
有机会可以学习下node~
