### ISSUE TITLE
tags 没有正常显示

### ISSUE THREAD

**Issue by Harteyang** [gary-Shen/hexo-theme-curry#20]
tags标签没有正常归档相关文章，点击直接跳转到所有归档的页面。

**Comment by gary-Shen** [comment]
怎么复现的呢？

**Comment by Harteyang** [comment]
比如从你的提供的[Live Demo](http://www.garyshen.com/)进去，点击第一篇文章的tag，#thoughts如下图，跳转的结果是归档，不是tags的归类。如下图。

<img width="561" alt="企业微信截图_49e3568a-502e-4336-872a-35b31671e41b" src="https://github.com/gary-Shen/hexo-theme-bear/assets/4878531/42ade962-59aa-4766-ae9a-5843a482863e">
<img width="578" alt="企业微信截图_445e4c18-9a7d-4def-abae-2ad39e9e94b4" src="https://github.com/gary-Shen/hexo-theme-bear/assets/4878531/79afb25e-9c6f-4263-9bdf-c92197b62397">

**Comment by gary-Shen** [comment]
OK，晚点更新一下~

**Comment by gary-Shen** [comment]
@Harteyang 
`git pul` 更新一下看看。

**Comment by Harteyang** [comment]
已更新，辛苦🙏
