### ISSUE TITLE
安装不上-是缺少依赖吗？

### ISSUE THREAD

**Issue by wwm0609** [gary-Shen/hexo-theme-curry#3]
请问下，clone了主题后，需要安装其他依赖吗？
我在_config.xml的theme设置成了curry,
然后 hexo clean; hexo g; hexo s; 预览页面有点
<img width="1143" alt="2018-04-07 13 07 50" src="https://user-images.githubusercontent.com/35440923/38451563-cdb7173a-3a64-11e8-943e-4c99a66bd051.png">
不正常

--hexo新手

**Comment by gary-Shen** [comment]
@wwm0609 抱歉现在才回复你😞，需要的依赖在[package.json](https://github.com/gary-Shen/hexo-theme-curry/blob/master/package.json)。
拷贝到curry目录下的package.json然后运行`npm install`。

**Comment by wwm0609** [comment]
谢谢回复，我晚上回家试试
