### ISSUE TITLE
代码片段有黑线。。。大神同志。。。我很仰慕你。。。

### ISSUE THREAD

**Issue by muchengdong** [gary-Shen/hexo-theme-curry#5]
代码片段这里有个问题，有黑边。。。很丑的样子。。。哈哈
![tim 20180423104138](https://user-images.githubusercontent.com/5198378/39104467-7895ae48-46e3-11e8-86c7-a076924e2d61.png)
我看到下面的css有一个border的设置
![tim 20180423104208](https://user-images.githubusercontent.com/5198378/39104527-b66fbbaa-46e3-11e8-98d8-011869d3be54.png)
去掉这个border之后就好看很多了。。。不知道去掉会不会有其他影响。。。
![tim 20180423104230](https://user-images.githubusercontent.com/5198378/39104572-e79c3e2e-46e3-11e8-998d-386ee9de4cfd.png)

**Comment by gary-Shen** [comment]
@fuzhouxxdong 你写的是行内代码吧？
### 行内代码：
<pre>
`Inline codes here.`
</pre>
### 代码块：
<pre>
```javascript
const foo = baz => bar => (bar + baz);
```
</pre>

**Comment by muchengdong** [comment]
空四格和三个点的效果一样吗？

**Comment by gary-Shen** [comment]
@fuzhouxxdong 多行代码建议使用“```”。没用过空四格。

**Comment by muchengdong** [comment]
好的 ，thx

**Comment by gary-Shen** [comment]
😊
