### ISSUE TITLE
disqus 评论框无法显示?

### ISSUE THREAD

**Issue by zakokun** [gary-Shen/hexo-theme-curry#7]
在_config 中设置了 disqus_shortname 了 但是依然不显示评论 是啥原因呢? pug 的代码我也不太会改....

**Comment by gary-Shen** [comment]
可能因为`disqus_shortname`不正确或disqus设置不正确。
[评论代码](https://github.com/gary-Shen/hexo-theme-curry/blob/master/layout/post.pug#L30)  
[Add Disqus Comments to Your Hexo Site 👉 第一步](https://equalsequals.io/2017/12/13/how-to-add-disqus-comments-to-hexo-blog/)

**Comment by zakokun** [comment]
这一段 block js 代码是怎么工作的?  我把这一段复制到上面的 `if !index && config.disqus_shortname`  逻辑内部就能正常工作了  
```
block js
  include ../_partial/post_footer.pug
  != js('script/post')
  if config.disqus_shortname
    script
      | var disqus_shortname = '!{config.disqus_shortname}';
      if page.permalink
        | var disqus_url = '!{page.permalink}';
        | (function(){
        |  var dsq = document.createElement('script');
        |  dsq.type = 'text/javascript';
        |  dsq.async = true;
        |  dsq.src = '//' + disqus_shortname + '.disqus.com/!{page.comments ? 'embed.js' : 'count.hs'}';
        |  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        | })();
```

很喜欢 bear 这个笔记, 你的主题也非常好看!

**Comment by zakokun** [comment]
还有个问题是,我最早的是2014年的文章, 首页往下翻能看到 但是在归档页中,只显示到2015年 这个是什么原因? 看 archive.pug 的代码感觉没啥问题啊

**Comment by zakokun** [comment]
> 还有个问题是,我最早的是2014年的文章, 首页往下翻能看到 但是在归档页中,只显示到2015年 这个是什么原因? 看 archive.pug 的代码感觉没啥问题啊

找到问题了, 因为 archive 没有分页 所以项目的per_page 设置会影响显示的数量
